### ISSUE TITLE
Minor issue in loadstore_trace.cpp 

### ISSUE THREAD

**Issue by wogus20002** [CMU-SAFARI/ramulator2#10]
https://github.com/CMU-SAFARI/ramulator2/blob/d56fd74841a2c1c5d26002a1ba6b8ca6d2d64e9d/src/frontend/impl/memory_trace/loadstore_trace.cpp#L43

It seems that Read and Write should be swapped in this line.

**Comment by RichardLuo79** [comment]
Hi Jaehyun,

Thanks for spotting this issue! We have fixed this in the latest commit.
