### ISSUE TITLE
Stuck at 93%

### ISSUE THREAD

**Issue by Ranyang-Zhou** [CMU-SAFARI/ramulator2#13]
Hi everyone,
I followed the instruction and typed 'make -j', the system stucked at 93%

"[ 93%] Building CXX object _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o"

Then the system dumped and nothing was installed.

Does anyone can give me an idea? Thanks a lot.

**Updated**: I ran the program on virtual tools and the version of Ubuntu is 22.04. I extended the memory size and it stucked at 95%.

[ 93%] Building CXX object _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
In file included from /usr/include/c++/12/ios:40,
                 from /usr/include/c++/12/istream:38,
                 from /usr/include/c++/12/sstream:38,
                 from /home/merlin/ramulator2/ext/yaml-cpp/src/singledocparser.cpp:3:
In static member function ‘static constexpr std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)’,
    inlined from ‘static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:431:21,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.tcc:532:22,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:1655:19,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:823:28,
    inlined from ‘void YAML::SingleDocParser::HandleNode(YAML::EventHandler&)’ at /home/merlin/ramulator2/ext/yaml-cpp/src/singledocparser.cpp:95:61:
/usr/include/c++/12/bits/char_traits.h:435:56: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Wrestrict]
  435 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

[ 95%] Linking CXX static library libyaml-cpp.a
[ 95%] Built target yaml-cpp

**Comment by ankenman** [comment]
It seems like you're stuck building the YAML library. Can you build it separately? Which CMake and compiler versions are you using?

**Comment by RichardLuo79** [comment]
Hi Ranyang,

What compiler toolchain are you using?
You could try removing everything under /ext and reconfigure & build the project.

**Comment by zifeng-yang** [comment]
Hi Ranyang,

I had a similar problem to yours, and I used “make -j2” then make ramulator successfully.
Try to add an even number after make j, if your core number more than one.

**Comment by RichardLuo79** [comment]
We were able to reproduce this issue on some computers.

It looks like `make -j` could cause very high CPU utilization during compilation, causing some systems to freeze. To avoid this, you can compile with less number of concurrent jobs (less than the number of cores of your CPU).
