### ISSUE TITLE
Missing gen_all_traces.sh script

### ISSUE THREAD

**Issue by KueipoH** [CMU-SAFARI/ramulator2#2]
I hope this message finds you well. I have been exploring ramulator2 repository and found the README instructions to be very informative. However, I encountered an issue when attempting to follow the steps mentioned in the README.

Specifically, in the section related to the "traces" directory, it is mentioned to run the command `./gen_all_traces.sh` However, upon closer inspection, I noticed that the `gen_all_traces.sh`"script is missing from the repository. 
As a result, I'm unable to proceed with generating the traces as described in the README.

Could someone kindly provide more information about the missing script or suggest an alternative approach to generating the traces?

**Comment by RichardLuo79** [comment]
Sorry for this! We forgot to include some files when preparing for the public version. Now we have added the missing script back.
