### ISSUE TITLE
uint not a type

### ISSUE THREAD

**Issue by jarrett-m** [CMU-SAFARI/ramulator2#24]
### Expected Behavior
Compile using cmake and g++13
### Current Behavior
Failed to compile; error given:

```
ramulator2/src/frontend/frontend.h:21:5: error: 'uint' does not name a type; did you mean 'int'?
   21 |     uint m_clock_ratio = 1;
```
   
```
ramulator2/src/memory_system/memory_system.h:22:5: error: 'uint' does not name a type; did you mean 'int'?
   22 |     uint m_clock_ratio = 1;
```

### Possible Solution

Replacing 'uint' with `unsigned int` fixed the issue. 

### Steps to Reproduce
Clone and run...
` $ mkdir build `
  `$ cd build ` 
  `$ cmake .. `
  `$ make -j `

### Environment
M2 Macbook Air
macOS Sonoma 14.1.1
gcc 13.2.0
Target: aarch64-apple-darwin22

**Comment by RichardLuo79** [comment]
Hi,

I have added the definition for `uint` to `base/base.h`

```c++
#ifndef uint
#define uint unsigned int
#endif
```
