### ISSUE TITLE
Potential Incorrect Density Setting in HBM2/3 Implementation

### ISSUE THREAD

**Issue by hwpeng** [CMU-SAFARI/ramulator2#26]
Encountered an error when running the 8Gb HBM2 and 3 configurations, as depicted in the screenshot:

<img width="969" alt="Screenshot 2023-11-14 at 9 38 05 AM" src="https://github.com/CMU-SAFARI/ramulator2/assets/8360695/88cbed6b-0194-4678-8d49-40048a324c52">

Upon inspecting the implementation, I found
https://github.com/CMU-SAFARI/ramulator2/blob/b7c70275f04126c647edb989270cc429776955d1/src/dram/impl/HBM3.cpp#L14

https://github.com/CMU-SAFARI/ramulator2/blob/b7c70275f04126c647edb989270cc429776955d1/src/dram/impl/HBM2.cpp#L14

It seems the density should be `8<<10` instead of `6<<10`?

I have tested other versions of HBM2/3, and they appear to be functioning correctly.

**Comment by RichardLuo79** [comment]
Hi,

Thanks for reporting this, we have fixed this in commit b05b6f6
