### ISSUE TITLE
I have a question about the value of "PBR2ACT" in the LPDDR5 device timing constraints.

### ISSUE THREAD

**Issue by najun-auto** [CMU-SAFARI/ramulator2#28]
` {.level = "rank", .preceding = {"ACT-1"},   .following = {"REFpb"}, .latency = V("nPBR2ACT")},  `

Shouldn't the above definition be modified to the following according to the specification?

`{.level = "rank", .preceding = {"REFpb"},   .following = {"ACT-1"}, .latency = V("nPBR2ACT")},
`

**Comment by RichardLuo79** [comment]
Thanks, this has been fixed.
