### ISSUE TITLE
error in state update of LPDDR5

### ISSUE THREAD

**Issue by sungmin-yun** [CMU-SAFARI/ramulator2#32]
https://github.com/CMU-SAFARI/ramulator2/blob/b7c70275f04126c647edb989270cc429776955d1/src/dram/impl/LPDDR5.cpp#L397-L423

In command such as CASRD, CASWR, RD16, and WR16, the *m_final_synced_cycle* should be updated with *m_timing_vals*, not *m_timing*. Current codes result in issuing WCK2CK command per every RD or WR request.

The code should be 

node->m_final_synced_cycle = clk + node->m_spec->m_timing_vals("nCL") + node->m_spec->m_timing_vals("nBL16") + 1;

**Comment by RichardLuo79** [comment]
Thank you! This has been fixed.
