### ISSUE TITLE
Compilation Error due to ranges library

### ISSUE THREAD

**Issue by Upasna55** [CMU-SAFARI/ramulator2#4]
Hello All

I am using cmake version 3.16.3. While executing `make -j`  in `ramulator2/build`, I am getting the following error due to `ranges` library:

<img width="960" alt="Screenshot 2023-08-30 152959" src="https://github.com/CMU-SAFARI/ramulator2/assets/91068864/c4c05d9a-627c-4273-8d26-3289a28dc0fd">

Would be grateful for any help in this regard.

Best Regards
Upasna

**Comment by RichardLuo79** [comment]
Hi Upasna,

Which compiler are you using?

**Comment by Upasna55** [comment]
Hello Richard

Thanks for your reply. It was indeed a compiler version issue.

Best Regards
Upasna
