### ISSUE TITLE
LPDDR5 doesn't compile

### ISSUE THREAD

**Issue by ankenman** [CMU-SAFARI/ramulator2#9]
I added LPDDR5.cpp to the dram CMakeLists and now run into compiler errors. Is this a known issue? I assume so because it seems intentionally left off of the source files.

    In file included from /ramulator/src/dram/dram.h:10,
                     from /ramulator/src/dram/impl/LPDDR5.cpp:1:
    /ramulator/src/dram/spec.h: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:414:78:   in ‘constexpr’ expansion of ‘Ramulator::LPDDR5::m_timings.Ramulator::ImplDef<21>::operator[](std::basic_string_view<char>(((const char*)"nBL")))’
    /ramulator/src/dram/spec.h:157:7: error: expression ‘<throw-expression>’ is not a constant expression
      157 |       throw "NON EXISTENT NAME";
          |       ^~~~~~~~~~~~~~~~~~~~~~~~~
    /ramulator/src/dram/spec.h: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:417:79:   in ‘constexpr’ expansion of ‘Ramulator::LPDDR5::m_timings.Ramulator::ImplDef<21>::operator[](std::basic_string_view<char>(((const char*)"nBL")))’
    /ramulator/src/dram/spec.h:157:7: error: expression ‘<throw-expression>’ is not a constant expression
    /ramulator/src/dram/spec.h: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:420:78:   in ‘constexpr’ expansion of ‘Ramulator::LPDDR5::m_timings.Ramulator::ImplDef<21>::operator[](std::basic_string_view<char>(((const char*)"nBL")))’
    /ramulator/src/dram/spec.h:157:7: error: expression ‘<throw-expression>’ is not a constant expression
    /ramulator/src/dram/spec.h: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:423:79:   in ‘constexpr’ expansion of ‘Ramulator::LPDDR5::m_timings.Ramulator::ImplDef<21>::operator[](std::basic_string_view<char>(((const char*)"nBL")))’
    /ramulator/src/dram/spec.h:157:7: error: expression ‘<throw-expression>’ is not a constant expression
    /ramulator/src/dram/impl/LPDDR5.cpp: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:427:25: error: ‘T’ has not been declared
      427 |         node->m_state = T::m_states["Pre-Opened"];
          |                         ^
    /ramulator/src/dram/impl/LPDDR5.cpp:428:40: error: ‘T’ has not been declared
      428 |         node->m_row_state[target_id] = T::m_states["Pre-Opened"];
          |                                        ^
    /ramulator/src/dram/impl/LPDDR5.cpp: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:445:16: error: ‘T’ has not been declared
      445 |           case T::m_states["Closed"]: return T::m_commands["ACT-1"];
          |                ^
    /ramulator/src/dram/impl/LPDDR5.cpp:445:46: error: ‘T’ has not been declared
      445 |           case T::m_states["Closed"]: return T::m_commands["ACT-1"];
          |                                              ^
    /ramulator/src/dram/impl/LPDDR5.cpp:446:16: error: ‘T’ has not been declared
      446 |           case T::m_states["Pre-Opened"]: return T::m_commands["ACT-2"];
          |                ^
    /ramulator/src/dram/impl/LPDDR5.cpp:446:50: error: ‘T’ has not been declared
      446 |           case T::m_states["Pre-Opened"]: return T::m_commands["ACT-2"];
          |                                                  ^
    /ramulator/src/dram/impl/LPDDR5.cpp:447:16: error: ‘T’ has not been declared
      447 |           case T::m_states["Opened"]: {
          |                ^
    /ramulator/src/dram/impl/LPDDR5.cpp:451:24: error: ‘T’ has not been declared
      451 |                 return T::m_commands["CASRD"];
          |                        ^
    /ramulator/src/dram/impl/LPDDR5.cpp:456:22: error: ‘T’ has not been declared
      456 |               return T::m_commands["PRE"];
          |                      ^
    /ramulator/src/dram/impl/LPDDR5.cpp: In lambda function:
    /ramulator/src/dram/impl/LPDDR5.cpp:467:16: error: ‘T’ has not been declared
      467 |           case T::m_states["Closed"]: return T::m_commands["ACT-1"];
          |                ^
    /ramulator/src/dram/impl/LPDDR5.cpp:467:46: error: ‘T’ has not been declared
      467 |           case T::m_states["Closed"]: return T::m_commands["ACT-1"];
          |                                              ^
    /ramulator/src/dram/impl/LPDDR5.cpp:468:16: error: ‘T’ has not been declared
      468 |           case T::m_states["Pre-Opened"]: return T::m_commands["ACT-2"];
          |                ^
    /ramulator/src/dram/impl/LPDDR5.cpp:468:50: error: ‘T’ has not been declared
      468 |           case T::m_states["Pre-Opened"]: return T::m_commands["ACT-2"];
          |                                                  ^
    /ramulator/src/dram/impl/LPDDR5.cpp:469:16: error: ‘T’ has not been declared
      469 |           case T::m_states["Opened"]: {
          |                ^
    /ramulator/src/dram/impl/LPDDR5.cpp:473:24: error: ‘T’ has not been declared
      473 |                 return T::m_commands["CASWR"];
          |                        ^
    /ramulator/src/dram/impl/LPDDR5.cpp:478:22: error: ‘T’ has not been declared
      478 |               return T::m_commands["PRE"];
          |

**Comment by RichardLuo79** [comment]
Sorry for this inconvenience! We missed some files when preparing the public version. The latest commit should have gotten rid of these stale files.
